"""Generate the grain field: geometry, adjacency, and the anneal CSS.
Run: python scripts/gen-grain.py   (needs numpy, scipy, shapely)
Deterministic — same seed gives the same field. Re-run only if you want a new field,
and commit the outputs so the build has no Python dependency."""

import json, random
import numpy as np
from scipy.spatial import Voronoi
from shapely.geometry import Polygon, box

SEED, COLS, ROWS, W, H, JITTER = 7, 9, 5, 1200, 600, 0.30
OPACITY_LO, OPACITY_HI = 0.028, 0.105

def build():
    rng = np.random.default_rng(SEED)
    pts = np.array([[(i + .5) * W / COLS + rng.uniform(-JITTER, JITTER) * W / COLS,
                     (j + .5) * H / ROWS + rng.uniform(-JITTER, JITTER) * H / ROWS]
                    for i in range(COLS) for j in range(ROWS)])

    # Mirror across all four edges so the boundary cells come out finite.
    mir = [pts]
    for sx, sy, ox, oy in [(-1, 1, 0, 0), (-1, 1, 2 * W, 0), (1, -1, 0, 0), (1, -1, 0, 2 * H)]:
        m = pts.copy(); m[:, 0] = sx * m[:, 0] + ox; m[:, 1] = sy * m[:, 1] + oy
        mir.append(m)

    vor, n, clip = Voronoi(np.vstack(mir)), len(pts), box(0, 0, W, H)
    paths = {}
    for k in range(n):
        reg = vor.regions[vor.point_region[k]]
        if not reg or -1 in reg:
            continue
        poly = Polygon([vor.vertices[i] for i in reg]).intersection(clip)
        if poly.is_empty or poly.geom_type != "Polygon":
            continue
        xs, ys = poly.exterior.coords.xy
        paths[int(k)] = "M" + "L".join(f"{x:.0f} {y:.0f}" for x, y in zip(xs, ys)) + "Z"

    adj = {k: set() for k in paths}
    for r in vor.ridge_points:
        a, b = int(r[0]), int(r[1])
        if a < n and b < n and a in paths and b in paths:
            adj[a].add(b); adj[b].add(a)
    return paths, {k: sorted(v) for k, v in adj.items()}


def facet_opacities(paths, adj, seed=3, iters=6000):
    """Per-cell fill opacity, evenly spread in value AND in space.

    Two steps, and they are different things:

    1. STRATIFIED SAMPLE — one draw per equal-probability stratum, so the full
       opacity range is covered with no gaps. (Latin hypercube is the name for
       the multidimensional version of this; in one dimension it is just a
       stratified sample.) This fixes value coverage. It says nothing about
       WHICH cell gets which value.

    2. BLUE NOISE — the actual fix for clumping. Swap values between cells to
       maximise the opacity gap across every shared boundary, so two dark cells
       are never adjacent. "Blue noise" is the term for a distribution that is
       random but free of clusters and voids; this is a cheap relaxation toward it.

    A plain shuffle gives clumps. Modular arithmetic (k * 37 % 8) gives a visible
    checkerboard, because periodic reads as periodic.
    """
    keys, rng = list(paths), random.Random(seed)
    n = len(keys)
    vals = [OPACITY_LO + (OPACITY_HI - OPACITY_LO) * ((i + rng.random()) / n) for i in range(n)]
    rng.shuffle(vals)
    v = dict(zip(keys, vals))

    def local(k):
        return sum(abs(v[k] - v[x]) for x in adj[k])

    for _ in range(iters):
        a, b = rng.sample(keys, 2)
        before = local(a) + local(b)
        v[a], v[b] = v[b], v[a]
        if local(a) + local(b) < before:
            v[a], v[b] = v[b], v[a]      # revert: the swap made neighbours more similar
    return v


paths, adj = build()
op = facet_opacities(paths, adj)

with open("src/generated/grain.json", "w") as f:
    json.dump({"viewBox": f"0 0 {W} {H}",
               "cells": [{"id": f"g{k}", "d": paths[k], "o": round(op[k], 4)}
                         for k in sorted(paths)]}, f, indent=1)

# One rule per cell. NOTE the :is() — see §3.3 for why a comma list is wrong here.
with open("src/generated/anneal.css", "w") as f:
    f.write("/* generated by scripts/gen-grain.py — do not edit */\n")
    f.write("@media (hover: hover) {\n")
    for k in sorted(adj):
        if not adj[k]:
            continue
        nb = ",".join(f"#g{x}" for x in adj[k])
        f.write(f"  .grain svg:has(#g{k}:hover) :is({nb}) {{ fill: var(--grain-soft); }}\n")
    f.write("}\n")

edges = [(a, b) for a in adj for b in adj[a] if a < b]
print(f"{len(paths)} cells, {len(edges)} boundaries, "
      f"min neighbour opacity gap {min(abs(op[a]-op[b]) for a, b in edges):.4f}")
